[phases.setup]
nixPkgs = ["python311", "nodejs-18_x"]

[phases.install]
cmds = [
  "cd backend && pip install -r requirements.txt",
  "cd frontend && npm install"
]

[phases.build]
cmds = [
  "cd backend && python download_nltk_resources.py",
  "cd frontend && npm run build"
]

[start]
cmd = "python serve.py"
